version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-app:latest
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - file-network
    restart: always

networks:
  file-network:
    driver: bridge
